//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhino.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rhino.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method &quot;{0}&quot;: name &quot;{1}&quot; is already in use..
        /// </summary>
        internal static string duplicate_defineClass_name {
            get {
                return ResourceManager.GetString("duplicate.defineClass.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IMPLEMENTATION.VERSION@.
        /// </summary>
        internal static string implementation_version {
            get {
                return ResourceManager.GetString("implementation.version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to Java class &quot;{0}&quot; is prohibited..
        /// </summary>
        internal static string msg_access_prohibited {
            get {
                return ResourceManager.GetString("msg.access.prohibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaAdapter requires at least one argument..
        /// </summary>
        internal static string msg_adapter_zero_args {
            get {
                return ResourceManager.GetString("msg.adapter.zero.args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add a property to a sealed object: {0}..
        /// </summary>
        internal static string msg_add_sealed {
            get {
                return ResourceManager.GetString("msg.add.sealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already executing generator.
        /// </summary>
        internal static string msg_already_exec_gen {
            get {
                return ResourceManager.GetString("msg.already.exec.gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous import: &quot;{0}&quot; and and &quot;{1}&quot;..
        /// </summary>
        internal static string msg_ambig_import {
            get {
                return ResourceManager.GetString("msg.ambig.import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeError: anonymous generator function returns a value.
        /// </summary>
        internal static string msg_anon_generator_returns {
            get {
                return ResourceManager.GetString("msg.anon.generator.returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anonymous function does not always return a value.
        /// </summary>
        internal static string msg_anon_no_return_value {
            get {
                return ResourceManager.GetString("msg.anon.no.return.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second argument to Function.prototype.apply must be an array.
        /// </summary>
        internal static string msg_arg_isnt_array {
            get {
                return ResourceManager.GetString("msg.arg.isnt.array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected argument of type object, but instead had type {0}.
        /// </summary>
        internal static string msg_arg_not_object {
            get {
                return ResourceManager.GetString("msg.arg.not.object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate array length..
        /// </summary>
        internal static string msg_arraylength_bad {
            get {
                return ResourceManager.GetString("msg.arraylength.bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length {0} exceeds supported capacity limit..
        /// </summary>
        internal static string msg_arraylength_too_big {
            get {
                return ResourceManager.GetString("msg.arraylength.too.big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment to undeclared variable {0}.
        /// </summary>
        internal static string msg_assn_create_strict {
            get {
                return ResourceManager.GetString("msg.assn.create.strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assignment left-hand side..
        /// </summary>
        internal static string msg_bad_assign_left {
            get {
                return ResourceManager.GetString("msg.bad.assign.left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back-reference exceeds number of capturing parentheses..
        /// </summary>
        internal static string msg_bad_backref {
            get {
                return ResourceManager.GetString("msg.bad.backref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlabelled break must be inside loop or switch.
        /// </summary>
        internal static string msg_bad_break {
            get {
                return ResourceManager.GetString("msg.bad.break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid catch block condition.
        /// </summary>
        internal static string msg_bad_catchcond {
            get {
                return ResourceManager.GetString("msg.bad.catchcond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction of objects of type &quot;{0}&quot; is not supported..
        /// </summary>
        internal static string msg_bad_ctor_return {
            get {
                return ResourceManager.GetString("msg.bad.ctor.return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found constructor with wrong signature: {0} calling {1} with signature {2}.
        /// </summary>
        internal static string msg_bad_ctor_sig {
            get {
                return ResourceManager.GetString("msg.bad.ctor.sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid decrement operand..
        /// </summary>
        internal static string msg_bad_decr {
            get {
                return ResourceManager.GetString("msg.bad.decr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object&apos;&apos;s getDefaultValue() method returned an object..
        /// </summary>
        internal static string msg_bad_default_value {
            get {
                return ResourceManager.GetString("msg.bad.default.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid destructuring assignment operator.
        /// </summary>
        internal static string msg_bad_destruct_op {
            get {
                return ResourceManager.GetString("msg.bad.destruct.op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid string escape mask.
        /// </summary>
        internal static string msg_bad_esc_mask {
            get {
                return ResourceManager.GetString("msg.bad.esc.mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left hand side of for..in loop must be an array of length 2 to accept key/value pair..
        /// </summary>
        internal static string msg_bad_for_in_destruct {
            get {
                return ResourceManager.GetString("msg.bad.for.in.destruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid left-hand side of for..in loop..
        /// </summary>
        internal static string msg_bad_for_in_lhs {
            get {
                return ResourceManager.GetString("msg.bad.for.in.lhs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to define a property, getter {0} must have zero parameters or a single ScriptableObject parameter..
        /// </summary>
        internal static string msg_bad_getter_parms {
            get {
                return ResourceManager.GetString("msg.bad.getter.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid identifier for this use in strict mode..
        /// </summary>
        internal static string msg_bad_id_strict {
            get {
                return ResourceManager.GetString("msg.bad.id.strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid increment operand..
        /// </summary>
        internal static string msg_bad_incr {
            get {
                return ResourceManager.GetString("msg.bad.incr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid label.
        /// </summary>
        internal static string msg_bad_label {
            get {
                return ResourceManager.GetString("msg.bad.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported return type &quot;{0}&quot; in method &quot;{1}&quot;..
        /// </summary>
        internal static string msg_bad_method_return {
            get {
                return ResourceManager.GetString("msg.bad.method.return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not a valid default namespace statement. Syntax is: default xml namespace = EXPRESSION;.
        /// </summary>
        internal static string msg_bad_namespace {
            get {
                return ResourceManager.GetString("msg.bad.namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxError: invalid object initializer.
        /// </summary>
        internal static string msg_bad_object_init {
            get {
                return ResourceManager.GetString("msg.bad.object.init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal octal literal digit {0}; interpreting it as a decimal digit.
        /// </summary>
        internal static string msg_bad_octal_literal {
            get {
                return ResourceManager.GetString("msg.bad.octal.literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported parameter type &quot;{0}&quot; in method &quot;{1}&quot;..
        /// </summary>
        internal static string msg_bad_parms {
            get {
                return ResourceManager.GetString("msg.bad.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision {0} out of range..
        /// </summary>
        internal static string msg_bad_precision {
            get {
                return ResourceManager.GetString("msg.bad.precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid property id.
        /// </summary>
        internal static string msg_bad_prop {
            get {
                return ResourceManager.GetString("msg.bad.prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quantifier {0}.
        /// </summary>
        internal static string msg_bad_quant {
            get {
                return ResourceManager.GetString("msg.bad.quant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal radix {0}..
        /// </summary>
        internal static string msg_bad_radix {
            get {
                return ResourceManager.GetString("msg.bad.radix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range in character class..
        /// </summary>
        internal static string msg_bad_range {
            get {
                return ResourceManager.GetString("msg.bad.range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one argument may be specified if the first argument to RegExp.prototype.compile is a RegExp object..
        /// </summary>
        internal static string msg_bad_regexp_compile {
            get {
                return ResourceManager.GetString("msg.bad.regexp.compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid return.
        /// </summary>
        internal static string msg_bad_return {
            get {
                return ResourceManager.GetString("msg.bad.return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid switch statement.
        /// </summary>
        internal static string msg_bad_switch {
            get {
                return ResourceManager.GetString("msg.bad.switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line terminator is not allowed between the throw keyword and throw expression..
        /// </summary>
        internal static string msg_bad_throw_eol {
            get {
                return ResourceManager.GetString("msg.bad.throw.eol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed URI sequence..
        /// </summary>
        internal static string msg_bad_uri {
            get {
                return ResourceManager.GetString("msg.bad.uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing variable name.
        /// </summary>
        internal static string msg_bad_var {
            get {
                return ResourceManager.GetString("msg.bad.var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid variable initialization.
        /// </summary>
        internal static string msg_bad_var_init {
            get {
                return ResourceManager.GetString("msg.bad.var.init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yield must be in a function..
        /// </summary>
        internal static string msg_bad_yield {
            get {
                return ResourceManager.GetString("msg.bad.yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be both a data and an accessor descriptor..
        /// </summary>
        internal static string msg_both_data_and_accessor_desc {
            get {
                return ResourceManager.GetString("msg.both.data.and.accessor.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &quot;{0}&quot; must be called directly, and not by way of a function of another name..
        /// </summary>
        internal static string msg_cant_call_indirect {
            get {
                return ResourceManager.GetString("msg.cant.call.indirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;&apos;t convert to type &quot;{0}&quot;..
        /// </summary>
        internal static string msg_cant_convert {
            get {
                return ResourceManager.GetString("msg.cant.convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error instantiating ({0}): class {1} is interface or abstract.
        /// </summary>
        internal static string msg_cant_instantiate {
            get {
                return ResourceManager.GetString("msg.cant.instantiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any catch clauses following an unqualified catch are unreachable.
        /// </summary>
        internal static string msg_catch_unreachable {
            get {
                return ResourceManager.GetString("msg.catch.unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number format error.
        /// </summary>
        internal static string msg_caught_nfe {
            get {
                return ResourceManager.GetString("msg.caught.nfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the configurable attribute of &quot;{0}&quot; from false to true..
        /// </summary>
        internal static string msg_change_configurable_false_to_true {
            get {
                return ResourceManager.GetString("msg.change.configurable.false.to.true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the enumerable attribute of &quot;{0}&quot; because configurable is false..
        /// </summary>
        internal static string msg_change_enumerable_with_configurable_false {
            get {
                return ResourceManager.GetString("msg.change.enumerable.with.configurable.false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the get attribute of &quot;{0}&quot; because configurable is false..
        /// </summary>
        internal static string msg_change_getter_with_configurable_false {
            get {
                return ResourceManager.GetString("msg.change.getter.with.configurable.false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change &quot;{0}&quot; from an accessor property to a data property because configurable is false..
        /// </summary>
        internal static string msg_change_property_accessor_to_data_with_configurable_false {
            get {
                return ResourceManager.GetString("msg.change.property.accessor.to.data.with.configurable.false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change &quot;{0}&quot; from a data property to an accessor property because configurable is false..
        /// </summary>
        internal static string msg_change_property_data_to_accessor_with_configurable_false {
            get {
                return ResourceManager.GetString("msg.change.property.data.to.accessor.with.configurable.false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the set attribute of &quot;{0}&quot; because configurable is false..
        /// </summary>
        internal static string msg_change_setter_with_configurable_false {
            get {
                return ResourceManager.GetString("msg.change.setter.with.configurable.false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the value of attribute &quot;{0}&quot; because writable is false..
        /// </summary>
        internal static string msg_change_value_with_writable_false {
            get {
                return ResourceManager.GetString("msg.change.value.with.writable.false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the writable attribute of &quot;{0}&quot; from false to true because configurable is false..
        /// </summary>
        internal static string msg_change_writable_false_to_true_with_configurable_false {
            get {
                return ResourceManager.GetString("msg.change.writable.false.to.true.with.configurable.false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeError: redeclaration of const {0}..
        /// </summary>
        internal static string msg_const_redecl {
            get {
                return ResourceManager.GetString("msg.const.redecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The choice of Java constructor {0} matching JavaScript argument types ({1}) is ambiguous; candidate constructors are: {2}.
        /// </summary>
        internal static string msg_constructor_ambiguous {
            get {
                return ResourceManager.GetString("msg.constructor.ambiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue can only use labeles of iteration statements.
        /// </summary>
        internal static string msg_continue_nonloop {
            get {
                return ResourceManager.GetString("msg.continue.nonloop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue must be inside loop.
        /// </summary>
        internal static string msg_continue_outside {
            get {
                return ResourceManager.GetString("msg.continue.outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert {0} to {1}.
        /// </summary>
        internal static string msg_conversion_not_allowed {
            get {
                return ResourceManager.GetString("msg.conversion.not.allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;&apos;t define constructor or class {0} since more than one constructor has multiple parameters..
        /// </summary>
        internal static string msg_ctor_multiple_parms {
            get {
                return ResourceManager.GetString("msg.ctor.multiple.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor for &quot;{0}&quot; not found..
        /// </summary>
        internal static string msg_ctor_not_found {
            get {
                return ResourceManager.GetString("msg.ctor.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic {0} value not allowed..
        /// </summary>
        internal static string msg_cyclic_value {
            get {
                return ResourceManager.GetString("msg.cyclic.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find default value for object..
        /// </summary>
        internal static string msg_default_value {
            get {
                return ResourceManager.GetString("msg.default.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; constructor is deprecated..
        /// </summary>
        internal static string msg_deprec_ctor {
            get {
                return ResourceManager.GetString("msg.deprec.ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing = in destructuring declaration.
        /// </summary>
        internal static string msg_destruct_assign_no_init {
            get {
                return ResourceManager.GetString("msg.destruct.assign.no.init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double default label in the switch statement.
        /// </summary>
        internal static string msg_double_switch_default {
            get {
                return ResourceManager.GetString("msg.double.switch.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicated label.
        /// </summary>
        internal static string msg_dup_label {
            get {
                return ResourceManager.GetString("msg.dup.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; already defined in this object literal..
        /// </summary>
        internal static string msg_dup_obj_lit_prop_strict {
            get {
                return ResourceManager.GetString("msg.dup.obj.lit.prop.strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; already declared in this function..
        /// </summary>
        internal static string msg_dup_param_strict {
            get {
                return ResourceManager.GetString("msg.dup.param.strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate parameter name &quot;{0}&quot;..
        /// </summary>
        internal static string msg_dup_parms {
            get {
                return ResourceManager.GetString("msg.dup.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce of empty array with no initial value.
        /// </summary>
        internal static string msg_empty_array_reduce {
            get {
                return ResourceManager.GetString("msg.empty.array.reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test for equality (==) mistyped as assignment (=)?.
        /// </summary>
        internal static string msg_equal_as_assign {
            get {
                return ResourceManager.GetString("msg.equal.as.assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling eval() with anything other than a primitive string value will simply return the value. Is this what you intended?.
        /// </summary>
        internal static string msg_eval_nonstring {
            get {
                return ResourceManager.GetString("msg.eval.nonstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling eval() with anything other than a primitive string value is not allowed in strict mode..
        /// </summary>
        internal static string msg_eval_nonstring_strict {
            get {
                return ResourceManager.GetString("msg.eval.nonstring.strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must extend ScriptableObject in order to define property {1}..
        /// </summary>
        internal static string msg_extend_scriptable {
            get {
                return ResourceManager.GetString("msg.extend.scriptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing comma is not legal in an ECMA-262 object initializer.
        /// </summary>
        internal static string msg_extra_trailing_comma {
            get {
                return ResourceManager.GetString("msg.extra.trailing.comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraneous trailing semicolon.
        /// </summary>
        internal static string msg_extra_trailing_semi {
            get {
                return ResourceManager.GetString("msg.extra.trailing.semi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeError: redeclaration of function {0}..
        /// </summary>
        internal static string msg_fn_redecl {
            get {
                return ResourceManager.GetString("msg.fn.redecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find function {0}..
        /// </summary>
        internal static string msg_function_not_found {
            get {
                return ResourceManager.GetString("msg.function.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find function {0} in object {1}..
        /// </summary>
        internal static string msg_function_not_found_in {
            get {
                return ResourceManager.GetString("msg.function.not.found.in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeError: generator function {0} returns a value.
        /// </summary>
        internal static string msg_generator_returns {
            get {
                return ResourceManager.GetString("msg.generator.returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getter and setter must both be static or neither be static..
        /// </summary>
        internal static string msg_getter_static {
            get {
                return ResourceManager.GetString("msg.getter.static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation produced {0} syntax errors..
        /// </summary>
        internal static string msg_got_syntax_errors {
            get {
                return ResourceManager.GetString("msg.got.syntax.errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal character.
        /// </summary>
        internal static string msg_illegal_character {
            get {
                return ResourceManager.GetString("msg.illegal.character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing in after for.
        /// </summary>
        internal static string msg_in_after_for_name {
            get {
                return ResourceManager.GetString("msg.in.after.for.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;&apos;t use &apos;&apos;in&apos;&apos; on a non-object..
        /// </summary>
        internal static string msg_in_not_object {
            get {
                return ResourceManager.GetString("msg.in.not.object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}&quot; called on incompatible object..
        /// </summary>
        internal static string msg_incompat_call {
            get {
                return ResourceManager.GetString("msg.incompat.call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&apos;prototype&apos;&apos; property of {0} is not an object..
        /// </summary>
        internal static string msg_instanceof_bad_prototype {
            get {
                return ResourceManager.GetString("msg.instanceof.bad.prototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;&apos;t use &apos;&apos;instanceof&apos;&apos; on a non-object..
        /// </summary>
        internal static string msg_instanceof_not_object {
            get {
                return ResourceManager.GetString("msg.instanceof.not.object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is invalid..
        /// </summary>
        internal static string msg_invalid_date {
            get {
                return ResourceManager.GetString("msg.invalid.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Unicode escape sequence.
        /// </summary>
        internal static string msg_invalid_escape {
            get {
                return ResourceManager.GetString("msg.invalid.escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid iterator value.
        /// </summary>
        internal static string msg_invalid_iterator {
            get {
                return ResourceManager.GetString("msg.invalid.iterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid flag after regular expression.
        /// </summary>
        internal static string msg_invalid_re_flag {
            get {
                return ResourceManager.GetString("msg.invalid.re.flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JavaScript value of type {0}.
        /// </summary>
        internal static string msg_invalid_type {
            get {
                return ResourceManager.GetString("msg.invalid.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not defined..
        /// </summary>
        internal static string msg_is_not_defined {
            get {
                return ResourceManager.GetString("msg.is.not.defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a function, it is {1}..
        /// </summary>
        internal static string msg_isnt_function {
            get {
                return ResourceManager.GetString("msg.isnt.function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call property {0} in object {1}. It is not a function, it is &quot;{2}&quot;..
        /// </summary>
        internal static string msg_isnt_function_in {
            get {
                return ResourceManager.GetString("msg.isnt.function.in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an xml object..
        /// </summary>
        internal static string msg_isnt_xml_object {
            get {
                return ResourceManager.GetString("msg.isnt.xml.object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __iterator__ returned a primitive value.
        /// </summary>
        internal static string msg_iterator_primitive {
            get {
                return ResourceManager.GetString("msg.iterator.primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array index {0} is out of bounds [0..{1}]..
        /// </summary>
        internal static string msg_java_array_index_out_of_bounds {
            get {
                return ResourceManager.GetString("msg.java.array.index.out.of.bounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java arrays have no public instance fields or methods named &quot;{0}&quot;..
        /// </summary>
        internal static string msg_java_array_member_not_found {
            get {
                return ResourceManager.GetString("msg.java.array.member.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;&apos;t find converter method &quot;{0}&quot; on class {1}..
        /// </summary>
        internal static string msg_java_conversion_implicit_method {
            get {
                return ResourceManager.GetString("msg.java.conversion.implicit_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: type conversion of {0} to assign to {1} on {2} failed..
        /// </summary>
        internal static string msg_java_internal_field_type {
            get {
                return ResourceManager.GetString("msg.java.internal.field.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: attempt to access private/protected field &quot;{0}&quot;..
        /// </summary>
        internal static string msg_java_internal_private {
            get {
                return ResourceManager.GetString("msg.java.internal.private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java class &quot;{0}&quot; has no public instance field or method named &quot;{1}&quot;..
        /// </summary>
        internal static string msg_java_member_not_found {
            get {
                return ResourceManager.GetString("msg.java.member.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java method &quot;{0}&quot; cannot be assigned to..
        /// </summary>
        internal static string msg_java_method_assign {
            get {
                return ResourceManager.GetString("msg.java.method.assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;&apos;t find method {0}..
        /// </summary>
        internal static string msg_java_no_such_method {
            get {
                return ResourceManager.GetString("msg.java.no_such_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyntaxError: let declaration not directly within block.
        /// </summary>
        internal static string msg_let_decl_not_in_block {
            get {
                return ResourceManager.GetString("msg.let.decl.not.in.block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeError: redeclaration of variable {0}..
        /// </summary>
        internal static string msg_let_redecl {
            get {
                return ResourceManager.GetString("msg.let.redecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum {0} less than minimum.
        /// </summary>
        internal static string msg_max_lt_min {
            get {
                return ResourceManager.GetString("msg.max.lt.min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The choice of Java method {0}.{1} matching JavaScript argument types ({2}) is ambiguous; candidate methods are: {3}.
        /// </summary>
        internal static string msg_method_ambiguous {
            get {
                return ResourceManager.GetString("msg.method.ambiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}&quot; not found in &quot;{1}&quot;..
        /// </summary>
        internal static string msg_method_not_found {
            get {
                return ResourceManager.GetString("msg.method.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing exponent.
        /// </summary>
        internal static string msg_missing_exponent {
            get {
                return ResourceManager.GetString("msg.missing.exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ; after statement.
        /// </summary>
        internal static string msg_missing_semi {
            get {
                return ResourceManager.GetString("msg.missing.semi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify readonly property: {0}..
        /// </summary>
        internal static string msg_modify_readonly {
            get {
                return ResourceManager.GetString("msg.modify.readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify a property of a sealed object: {0}..
        /// </summary>
        internal static string msg_modify_sealed {
            get {
                return ResourceManager.GetString("msg.modify.sealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one variable allowed in for..in loop..
        /// </summary>
        internal static string msg_mult_index {
            get {
                return ResourceManager.GetString("msg.mult.index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace object expected to left of :: (found {0} instead).
        /// </summary>
        internal static string msg_namespace_expected {
            get {
                return ResourceManager.GetString("msg.namespace.expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing }} after function body.
        /// </summary>
        internal static string msg_no_brace_after_body {
            get {
                return ResourceManager.GetString("msg.no.brace.after.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing }} in compound statement.
        /// </summary>
        internal static string msg_no_brace_block {
            get {
                return ResourceManager.GetString("msg.no.brace.block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing &apos;{{&apos; before function body.
        /// </summary>
        internal static string msg_no_brace_body {
            get {
                return ResourceManager.GetString("msg.no.brace.body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing &apos;{{&apos; before catch-block body.
        /// </summary>
        internal static string msg_no_brace_catchblock {
            get {
                return ResourceManager.GetString("msg.no.brace.catchblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing } after property list.
        /// </summary>
        internal static string msg_no_brace_prop {
            get {
                return ResourceManager.GetString("msg.no.brace.prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing &apos;{{&apos; before switch body.
        /// </summary>
        internal static string msg_no_brace_switch {
            get {
                return ResourceManager.GetString("msg.no.brace.switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing &apos;{{&apos; before try block.
        /// </summary>
        internal static string msg_no_brace_try {
            get {
                return ResourceManager.GetString("msg.no.brace.try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ] after element list.
        /// </summary>
        internal static string msg_no_bracket_arg {
            get {
                return ResourceManager.GetString("msg.no.bracket.arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ] in index expression.
        /// </summary>
        internal static string msg_no_bracket_index {
            get {
                return ResourceManager.GetString("msg.no.bracket.index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing : after case expression.
        /// </summary>
        internal static string msg_no_colon_case {
            get {
                return ResourceManager.GetString("msg.no.colon.case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing : in conditional expression.
        /// </summary>
        internal static string msg_no_colon_cond {
            get {
                return ResourceManager.GetString("msg.no.colon.cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing : after property id.
        /// </summary>
        internal static string msg_no_colon_prop {
            get {
                return ResourceManager.GetString("msg.no.colon.prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing }} after let statement.
        /// </summary>
        internal static string msg_no_curly_let {
            get {
                return ResourceManager.GetString("msg.no.curly.let", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert function to interface {0} with no methods.
        /// </summary>
        internal static string msg_no_empty_interface_conversion {
            get {
                return ResourceManager.GetString("msg.no.empty.interface.conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert function to interface {0} since it contains methods with different names.
        /// </summary>
        internal static string msg_no_function_interface_conversion {
            get {
                return ResourceManager.GetString("msg.no.function.interface.conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no source found to decompile function reference {0}.
        /// </summary>
        internal static string msg_no_function_ref_found {
            get {
                return ResourceManager.GetString("msg.no.function.ref.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java constructor for &quot;{0}&quot; with arguments &quot;{1}&quot; not found..
        /// </summary>
        internal static string msg_no_java_ctor {
            get {
                return ResourceManager.GetString("msg.no.java.ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing name after :: operator.
        /// </summary>
        internal static string msg_no_name_after_coloncolon {
            get {
                return ResourceManager.GetString("msg.no.name.after.coloncolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing name after . operator.
        /// </summary>
        internal static string msg_no_name_after_dot {
            get {
                return ResourceManager.GetString("msg.no.name.after.dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing name after .. operator.
        /// </summary>
        internal static string msg_no_name_after_dotdot {
            get {
                return ResourceManager.GetString("msg.no.name.after.dotdot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing name after .@.
        /// </summary>
        internal static string msg_no_name_after_xmlAttr {
            get {
                return ResourceManager.GetString("msg.no.name.after.xmlAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octal numbers prohibited in strict mode..
        /// </summary>
        internal static string msg_no_octal_strict {
            get {
                return ResourceManager.GetString("msg.no.octal.strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}&quot; occurs multiple times in class &quot;{1}&quot;..
        /// </summary>
        internal static string msg_no_overload {
            get {
                return ResourceManager.GetString("msg.no.overload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) in parenthetical.
        /// </summary>
        internal static string msg_no_paren {
            get {
                return ResourceManager.GetString("msg.no.paren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) after condition.
        /// </summary>
        internal static string msg_no_paren_after_cond {
            get {
                return ResourceManager.GetString("msg.no.paren.after.cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ( after let.
        /// </summary>
        internal static string msg_no_paren_after_let {
            get {
                return ResourceManager.GetString("msg.no.paren.after.let", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) after formal parameters.
        /// </summary>
        internal static string msg_no_paren_after_parms {
            get {
                return ResourceManager.GetString("msg.no.paren.after.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) after switch expression.
        /// </summary>
        internal static string msg_no_paren_after_switch {
            get {
                return ResourceManager.GetString("msg.no.paren.after.switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) after with-statement object.
        /// </summary>
        internal static string msg_no_paren_after_with {
            get {
                return ResourceManager.GetString("msg.no.paren.after.with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) after argument list.
        /// </summary>
        internal static string msg_no_paren_arg {
            get {
                return ResourceManager.GetString("msg.no.paren.arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ( before catch-block condition.
        /// </summary>
        internal static string msg_no_paren_catch {
            get {
                return ResourceManager.GetString("msg.no.paren.catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ( before condition.
        /// </summary>
        internal static string msg_no_paren_cond {
            get {
                return ResourceManager.GetString("msg.no.paren.cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ( after for.
        /// </summary>
        internal static string msg_no_paren_for {
            get {
                return ResourceManager.GetString("msg.no.paren.for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) after for-loop control.
        /// </summary>
        internal static string msg_no_paren_for_ctrl {
            get {
                return ResourceManager.GetString("msg.no.paren.for.ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ) after variable list.
        /// </summary>
        internal static string msg_no_paren_let {
            get {
                return ResourceManager.GetString("msg.no.paren.let", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ( before function parameters..
        /// </summary>
        internal static string msg_no_paren_parms {
            get {
                return ResourceManager.GetString("msg.no.paren.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ( before switch expression.
        /// </summary>
        internal static string msg_no_paren_switch {
            get {
                return ResourceManager.GetString("msg.no.paren.switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ( before with-statement object.
        /// </summary>
        internal static string msg_no_paren_with {
            get {
                return ResourceManager.GetString("msg.no.paren.with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing formal parameter.
        /// </summary>
        internal static string msg_no_parm {
            get {
                return ResourceManager.GetString("msg.no.parm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no properties..
        /// </summary>
        internal static string msg_no_properties {
            get {
                return ResourceManager.GetString("msg.no.properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no input for {0}.
        /// </summary>
        internal static string msg_no_re_input_for {
            get {
                return ResourceManager.GetString("msg.no.re.input.for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function {0} can not be used as the left-hand side of assignment or as an operand of ++ or -- operator..
        /// </summary>
        internal static string msg_no_ref_from_function {
            get {
                return ResourceManager.GetString("msg.no.ref.from.function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a reference to read reference value..
        /// </summary>
        internal static string msg_no_ref_to_get {
            get {
                return ResourceManager.GetString("msg.no.ref.to.get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a reference to set reference value to {1}..
        /// </summary>
        internal static string msg_no_ref_to_set {
            get {
                return ResourceManager.GetString("msg.no.ref.to.set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions are not available..
        /// </summary>
        internal static string msg_no_regexp {
            get {
                return ResourceManager.GetString("msg.no.regexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function {0} does not always return a value.
        /// </summary>
        internal static string msg_no_return_value {
            get {
                return ResourceManager.GetString("msg.no.return.value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ; after for-loop initializer.
        /// </summary>
        internal static string msg_no_semi_for {
            get {
                return ResourceManager.GetString("msg.no.semi.for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ; after for-loop condition.
        /// </summary>
        internal static string msg_no_semi_for_cond {
            get {
                return ResourceManager.GetString("msg.no.semi.for.cond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing ; before statement.
        /// </summary>
        internal static string msg_no_semi_stmt {
            get {
                return ResourceManager.GetString("msg.no.semi.stmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has no side effects.
        /// </summary>
        internal static string msg_no_side_effects {
            get {
                return ResourceManager.GetString("msg.no.side.effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing while after do-loop body.
        /// </summary>
        internal static string msg_no_while_do {
            get {
                return ResourceManager.GetString("msg.no.while.do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with statements not allowed in strict mode.
        /// </summary>
        internal static string msg_no_with_strict {
            get {
                return ResourceManager.GetString("msg.no.with.strict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java method &quot;{0}&quot; was invoked with {1} as &quot;this&quot; value that can not be converted to Java type {2}..
        /// </summary>
        internal static string msg_nonjava_method {
            get {
                return ResourceManager.GetString("msg.nonjava.method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function importClass must be called with a class; had &quot;{0}&quot; instead..
        /// </summary>
        internal static string msg_not_class {
            get {
                return ResourceManager.GetString("msg.not.class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is neither a class nor a package..
        /// </summary>
        internal static string msg_not_class_not_pkg {
            get {
                return ResourceManager.GetString("msg.not.class.not.pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor for &quot;Packages&quot; expects argument of type java.lang.Classloader.
        /// </summary>
        internal static string msg_not_classloader {
            get {
                return ResourceManager.GetString("msg.not.classloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a constructor..
        /// </summary>
        internal static string msg_not_ctor {
            get {
                return ResourceManager.GetString("msg.not.ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add properties to this object because extensible is false..
        /// </summary>
        internal static string msg_not_extensible {
            get {
                return ResourceManager.GetString("msg.not.extensible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is not a function in interface adapter.
        /// </summary>
        internal static string msg_not_function_interface {
            get {
                return ResourceManager.GetString("msg.not.function.interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is not Java class: {1}..
        /// </summary>
        internal static string msg_not_java_class_arg {
            get {
                return ResourceManager.GetString("msg.not.java.class.arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected argument to getClass() to be a Java object..
        /// </summary>
        internal static string msg_not_java_obj {
            get {
                return ResourceManager.GetString("msg.not.java.obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function importPackage must be called with a package; had &quot;{0}&quot; instead..
        /// </summary>
        internal static string msg_not_pkg {
            get {
                return ResourceManager.GetString("msg.not.pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to an object..
        /// </summary>
        internal static string msg_null_to_object {
            get {
                return ResourceManager.GetString("msg.null.to.object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected static or delegated getter {0} to take a ScriptableObject parameter..
        /// </summary>
        internal static string msg_obj_getter_parms {
            get {
                return ResourceManager.GetString("msg.obj.getter.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; may only be invoked from a &quot;new&quot; expression..
        /// </summary>
        internal static string msg_only_from_new {
            get {
                return ResourceManager.GetString("msg.only.from.new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one class may be extended by a JavaAdapter. Had {0} and {1}..
        /// </summary>
        internal static string msg_only_one_super {
            get {
                return ResourceManager.GetString("msg.only.one.super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed..
        /// </summary>
        internal static string msg_op_not_allowed {
            get {
                return ResourceManager.GetString("msg.op.not.allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overly large back reference {0}.
        /// </summary>
        internal static string msg_overlarge_backref {
            get {
                return ResourceManager.GetString("msg.overlarge.backref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overly large maximum {0}.
        /// </summary>
        internal static string msg_overlarge_max {
            get {
                return ResourceManager.GetString("msg.overlarge.max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overly large minimum {0}.
        /// </summary>
        internal static string msg_overlarge_min {
            get {
                return ResourceManager.GetString("msg.overlarge.min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeError: redeclaration of formal parameter {0}..
        /// </summary>
        internal static string msg_parm_redecl {
            get {
                return ResourceManager.GetString("msg.parm.redecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java package names may not be numbers..
        /// </summary>
        internal static string msg_pkg_int {
            get {
                return ResourceManager.GetString("msg.pkg.int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primitive type expected (had {0} instead).
        /// </summary>
        internal static string msg_primitive_expected {
            get {
                return ResourceManager.GetString("msg.primitive.expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import &quot;{0}&quot; since a property by that name is already defined..
        /// </summary>
        internal static string msg_prop_defined {
            get {
                return ResourceManager.GetString("msg.prop.defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} not found..
        /// </summary>
        internal static string msg_prop_not_found {
            get {
                return ResourceManager.GetString("msg.prop.not.found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unmatched ) in regular expression..
        /// </summary>
        internal static string msg_re_unmatched_right_paren {
            get {
                return ResourceManager.GetString("msg.re.unmatched.right.paren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to undefined property &quot;{0}&quot;.
        /// </summary>
        internal static string msg_ref_undefined_prop {
            get {
                return ResourceManager.GetString("msg.ref.undefined.prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove a property from a sealed object: {0}..
        /// </summary>
        internal static string msg_remove_sealed {
            get {
                return ResourceManager.GetString("msg.remove.sealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identifier is a reserved word.
        /// </summary>
        internal static string msg_reserved_id {
            get {
                return ResourceManager.GetString("msg.reserved.id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegal usage of future reserved keyword {0}; interpreting it as ordinary identifier.
        /// </summary>
        internal static string msg_reserved_keyword {
            get {
                return ResourceManager.GetString("msg.reserved.keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return statement is inconsistent with previous usage.
        /// </summary>
        internal static string msg_return_inconsistent {
            get {
                return ResourceManager.GetString("msg.return.inconsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script objects are not constructors..
        /// </summary>
        internal static string msg_script_is_not_constructor {
            get {
                return ResourceManager.GetString("msg.script.is.not.constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to send value to newborn generator.
        /// </summary>
        internal static string msg_send_newborn {
            get {
                return ResourceManager.GetString("msg.send.newborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set property {0} that has only a getter..
        /// </summary>
        internal static string msg_set_prop_no_setter {
            get {
                return ResourceManager.GetString("msg.set.prop.no.setter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported parameter type &quot;{0}&quot; in setter &quot;{1}&quot;..
        /// </summary>
        internal static string msg_setter_bad_type {
            get {
                return ResourceManager.GetString("msg.setter.bad.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected either one or two parameters for setter..
        /// </summary>
        internal static string msg_setter_parms {
            get {
                return ResourceManager.GetString("msg.setter.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setter must have void return type: {0}.
        /// </summary>
        internal static string msg_setter_return {
            get {
                return ResourceManager.GetString("msg.setter.return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected single parameter setter for {0}.
        /// </summary>
        internal static string msg_setter1_parms {
            get {
                return ResourceManager.GetString("msg.setter1.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected static or delegated setter {0} to take two parameters..
        /// </summary>
        internal static string msg_setter2_expected {
            get {
                return ResourceManager.GetString("msg.setter2.expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-parameter setter must take a ScriptableObject as its first parameter..
        /// </summary>
        internal static string msg_setter2_parms {
            get {
                return ResourceManager.GetString("msg.setter2.parms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopIteration may not be changed to an arbitrary object..
        /// </summary>
        internal static string msg_StopIteration_invalid {
            get {
                return ResourceManager.GetString("msg.StopIteration.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syntax error.
        /// </summary>
        internal static string msg_syntax {
            get {
                return ResourceManager.GetString("msg.syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toISOString must return a primitive value, but instead returned &quot;{0}&quot;.
        /// </summary>
        internal static string msg_toisostring_must_return_primitive {
            get {
                return ResourceManager.GetString("msg.toisostring.must.return.primitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program too complex: internal index exceeds 64K limit..
        /// </summary>
        internal static string msg_too_big_index {
            get {
                return ResourceManager.GetString("msg.too.big.index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program too complex: too big jump offset..
        /// </summary>
        internal static string msg_too_big_jump {
            get {
                return ResourceManager.GetString("msg.too.big.jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too deep recursion while parsing.
        /// </summary>
        internal static string msg_too_deep_parser_recursion {
            get {
                return ResourceManager.GetString("msg.too.deep.parser.recursion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many constructor arguments.
        /// </summary>
        internal static string msg_too_many_constructor_args {
            get {
                return ResourceManager.GetString("msg.too.many.constructor.args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many function arguments.
        /// </summary>
        internal static string msg_too_many_function_args {
            get {
                return ResourceManager.GetString("msg.too.many.function.args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing \\ in regular expression..
        /// </summary>
        internal static string msg_trail_backslash {
            get {
                return ResourceManager.GetString("msg.trail.backslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing comma in array literal has different cross-browser behavior.
        /// </summary>
        internal static string msg_trailing_array_comma {
            get {
                return ResourceManager.GetString("msg.trailing.array.comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&apos;try&apos;&apos; without &apos;&apos;catch&apos;&apos; or &apos;&apos;finally&apos;&apos;.
        /// </summary>
        internal static string msg_try_no_catchfinally {
            get {
                return ResourceManager.GetString("msg.try.no.catchfinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined label.
        /// </summary>
        internal static string msg_undef_label {
            get {
                return ResourceManager.GetString("msg.undef.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call method &quot;{1}&quot; of {0}.
        /// </summary>
        internal static string msg_undef_method_call {
            get {
                return ResourceManager.GetString("msg.undef.method.call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete property &quot;{1}&quot; of {0}.
        /// </summary>
        internal static string msg_undef_prop_delete {
            get {
                return ResourceManager.GetString("msg.undef.prop.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read property &quot;{1}&quot; from {0}.
        /// </summary>
        internal static string msg_undef_prop_read {
            get {
                return ResourceManager.GetString("msg.undef.prop.read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set property &quot;{1}&quot; of {0} to &quot;{2}&quot;.
        /// </summary>
        internal static string msg_undef_prop_write {
            get {
                return ResourceManager.GetString("msg.undef.prop.write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert undefined to an object..
        /// </summary>
        internal static string msg_undef_to_object {
            get {
                return ResourceManager.GetString("msg.undef.to.object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply &quot;with&quot; to {0}.
        /// </summary>
        internal static string msg_undef_with {
            get {
                return ResourceManager.GetString("msg.undef.with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is not defined in interface adapter.
        /// </summary>
        internal static string msg_undefined_function_interface {
            get {
                return ResourceManager.GetString("msg.undefined.function.interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file.
        /// </summary>
        internal static string msg_unexpected_eof {
            get {
                return ResourceManager.GetString("msg.unexpected.eof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated character class {0}.
        /// </summary>
        internal static string msg_unterm_class {
            get {
                return ResourceManager.GetString("msg.unterm.class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated parenthetical {0}.
        /// </summary>
        internal static string msg_unterm_paren {
            get {
                return ResourceManager.GetString("msg.unterm.paren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated quantifier {0}.
        /// </summary>
        internal static string msg_unterm_quant {
            get {
                return ResourceManager.GetString("msg.unterm.quant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unterminated comment.
        /// </summary>
        internal static string msg_unterminated_comment {
            get {
                return ResourceManager.GetString("msg.unterminated.comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unterminated regular expression literal.
        /// </summary>
        internal static string msg_unterminated_re_lit {
            get {
                return ResourceManager.GetString("msg.unterminated.re.lit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unterminated string literal.
        /// </summary>
        internal static string msg_unterminated_string_lit {
            get {
                return ResourceManager.GetString("msg.unterminated.string.lit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} hides argument.
        /// </summary>
        internal static string msg_var_hides_arg {
            get {
                return ResourceManager.GetString("msg.var.hides.arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeError: redeclaration of var {0}..
        /// </summary>
        internal static string msg_var_redecl {
            get {
                return ResourceManager.GetString("msg.var.redecl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method or constructor &quot;{0}&quot; must be static with the signature &quot;(Context cx, Object[] args, Function ctorObj, boolean inNewExpr)&quot; to define a variable arguments constructor..
        /// </summary>
        internal static string msg_varargs_ctor {
            get {
                return ResourceManager.GetString("msg.varargs.ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &quot;{0}&quot; must be static with the signature &quot;(Context cx, Scriptable thisObj, Object[] args, Function funObj)&quot; to define a variable arguments function..
        /// </summary>
        internal static string msg_varargs_fun {
            get {
                return ResourceManager.GetString("msg.varargs.fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered code generation error while compiling function &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string msg_while_compiling_fn {
            get {
                return ResourceManager.GetString("msg.while.compiling.fn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered code generation error while compiling script: {0}.
        /// </summary>
        internal static string msg_while_compiling_script {
            get {
                return ResourceManager.GetString("msg.while.compiling.script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to illegally formed XML syntax.
        /// </summary>
        internal static string msg_XML_bad_form {
            get {
                return ResourceManager.GetString("msg.XML.bad.form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML runtime not available.
        /// </summary>
        internal static string msg_XML_not_available {
            get {
                return ResourceManager.GetString("msg.XML.not.available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield from closing generator.
        /// </summary>
        internal static string msg_yield_closing {
            get {
                return ResourceManager.GetString("msg.yield.closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yield expression must be parenthesized..
        /// </summary>
        internal static string msg_yield_parenthesized {
            get {
                return ResourceManager.GetString("msg.yield.parenthesized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load class &quot;{0}&quot; which has no zero-parameter constructor..
        /// </summary>
        internal static string msg_zero_arg_ctor {
            get {
                return ResourceManager.GetString("msg.zero.arg.ctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero quantifier {0}.
        /// </summary>
        internal static string msg_zero_quant {
            get {
                return ResourceManager.GetString("msg.zero.quant", resourceCulture);
            }
        }
    }
}
