/*
 * This code is derived from rhino (http://github.com/mozilla/rhino)
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

using System;
using Rhino;
using Sharpen;

namespace Rhino
{
	/// <summary>Interface to define classes from generated byte code.</summary>
	/// <remarks>Interface to define classes from generated byte code.</remarks>
	public interface GeneratedClassLoader
	{
		// API class
		/// <summary>Define a new Java class.</summary>
		/// <remarks>
		/// Define a new Java class.
		/// Classes created via this method should have the same class loader.
		/// </remarks>
		/// <param name="name">fully qualified class name</param>
		/// <param name="data">class byte code</param>
		/// <returns>new class object</returns>
		Type DefineClass(string name, byte[] data);

		/// <summary>Link the given class.</summary>
		/// <remarks>Link the given class.</remarks>
		/// <param name="cl">
		/// Class instance returned from the previous call to
		/// <see cref="DefineClass(string, byte[])">DefineClass(string, byte[])</see>
		/// </param>
		/// <seealso cref="Sharpen.ClassLoader">Sharpen.ClassLoader</seealso>
		void LinkClass(Type cl);
	}
}
